language: node_js
node_js:
- lts/*
script: npm run-script build
deploy:
- provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "test-site-roman"
  skip_cleanup: true
  on:
    branch: master
  env:
  - ENV=0
- provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: dev
  env:
  - ENV=1
env:
  - API_SERVER=$API_SERVER
