language: node_js
node_js:
- lts/*
script: npm run-script build
deploy:
- provider: firebase
  token: $FIREBASE_TOKEN
  project: meters-home
  skip_cleanup: true
  on:
    branch: master
- provider: firebase
  token: $FIREBASE_TOKEN
  project: meters-home-dev
  skip_cleanup: true
  on:
    branch: dev
env:
  - API_SERVER=$API_SERVER
  - ENV_ID=0
