language: node_js
node_js:
- lts/*
script: npm run-script build
deploy:
- provider: firebase
  token: $FIREBASE_TOKEN
  project: meters-home
  skip_cleanup: true
  on:
    branch: master
- provider: firebase
  token: $FIREBASE_TOKEN
  project: meters-home-dev
  skip_cleanup: true
  on:
    branch: dev
env:
  global:
    - API_SERVER=api_server
    - SOME_VALUE=0
  matrix:
    - ENV_ID=true
    - ENV_ID=false
