language: node_js
node_js:
- 'lts/*'
script: npm run-script build
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master
env:
  - API_SERVER=$API_SERVER