language: node_js
node_js:
- lts/*

env:
  global:
    - API_SERVER=api_server
      SOME_VALUE=0

jobs:
  include:
    - if: branch = master
      env: ENV_ID=0
    - if: branch = dev
      env: ENV_ID=1

script: npm run-script build

deploy:
- provider: firebase
  token: $FIREBASE_TOKEN
  project: meters-home
  skip_cleanup: true
  on:
    branch: master
- provider: firebase
  token: $FIREBASE_TOKEN
  project: meters-home-dev
  skip_cleanup: true
  on:
    branch: dev