language: node_js
node_js:
- 'lts/*'
script: npm run-script build
deploy:
  provider: script
  script: 
   - checkout
   - node --version
   - npm --version
   - npm install now -g
   - now --token=$NOW_TOKEN --name=meters --prod
  skip_cleanup: true
  on:
    branch: master
env:
  - API_SERVER=$API_SERVER